### ISSUE TITLE
No module named Qpip.qpip

### ISSUE THREAD

**Issue by dsegerss** [cnheider/eqip#4]
Hi,
Really interested in using this plugin, but installation does not seem to work properly. I install from the official experimental repository. When I activate the toolbar I get:
```
Couldn't load plugin 'Qpip' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'Qpip.qpip' 
Traceback (most recent call last):
  File "/app/share/qgis/python/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/a001080/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/Qpip/__init__.py", line 22, in classFactory
    from .plugin import QPip
  File "/app/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/a001080/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/Qpip/plugin.py", line 17, in 
    from .qpip import PLUGIN_DIR, PROJECT_NAME
  File "/app/share/qgis/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'Qpip.qpip'
```

**Desktop (please complete the following information):**
 - OS: linux (RHEL8), using flatpack installation
 - QGIS-version [e.g. 3.28.9]

Other plugins work fine, so I assume there is a bug in the currently published version?

**Comment by cnheider** [comment]
Hello, 
I apologise for the late response, I have not updated the plugin on the QGIS plugin index for quite a while. Qpip was the name of the earlier prototype of this plugin, I changed it due to some apparent collision with another plugin. 
Good news though, I have to continued development and testing internally, in the near future I will automate the releases of this plugin, until then feel free to install this plug-in directly from a zip of this repo 😄
